import { Memory, NarrativeStyle, Language } from './types';

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    appName: 'Ethereal Archivist',
    archive: 'Archive',
    journal: 'Journal',
    moments: 'Moments',
    settings: 'Settings',
    record: 'Record',
    chronologicalAnthology: 'Chronological Anthology',
    memoirTitle: "The Archivist's Memoir",
    memoirDesc: 'A curated sequence of echoes and light. Every memory is a fragment of the soul, preserved in the amber of time.',
    captureNew: 'Capture a new fragment?',
    journeyContinues: 'Your journey continues with every breath and observation.',
    recordNew: 'Record New Memory',
    recordTitle: 'Record Your Story',
    recordDesc: 'Speak softly. The moment is yours to keep forever.',
    listening: 'Listening for silence...',
    promptLabel: 'Prompt of the day',
    promptText: '"What did the morning light reveal to you today?"',
    insightLabel: 'Memory Insight',
    insightText: 'AI will categorize this memory as ',
    sensoryReflection: 'Sensory Reflection',
    tipTitle: 'Archivist Tip',
    tipText: "Don't worry about the structure. Simply describe the colors, smells, and feelings. I'll weave them into a narrative later.",
    selectionLabel: 'Selection',
    styleTitle: 'Narrative Style',
    styleDesc: 'Choose Your Narrative Style',
    beginTranscription: 'Begin Transcription',
    skipForNow: 'Skip for now',
    archivalActive: 'Archival Process Active',
    transcribingTitle: 'Transcribing your whispers into silk...',
    weavingSilk: 'Weaving your memory into silk...',
    silkWoven: 'Your memory has been woven.',
    poeticQuote: '"Memories are fragile; we weave them into a tapestry that time cannot fray."',
    audioMode: 'Audio Mode',
    textMode: 'Text Mode',
    textPlaceholder: 'Type your memory here...',
    writing: 'Writing your thoughts...',
    journalDesc: 'Your personal narrative journey, captured in whispers and silk.',
    entryLabel: 'Entry',
    settingsDesc: 'Customize your archival experience.',
    profileSettings: 'Profile Settings',
    profileSettingsDesc: 'Manage your personal information and archival identity.',
    notifications: 'Notifications',
    notificationsDesc: 'Control how and when you receive archival reminders.',
    privacySecurity: 'Privacy & Security',
    privacySecurityDesc: 'Your memories are sacred. Manage your data protection.',
    languageRegion: 'Language & Region',
    languageRegionDesc: 'Adjust your preferred language and regional settings.',
    defaultTranscript: 'A quiet moment of reflection under the soft glow of the afternoon sun.',
    currentFragment: 'Current Fragment',
    springAfternoon: 'The Spring Afternoon, 1994',
    springDesc: "The scent of rain on dry pavement lingered in the air as we sat on the porch. The world was quiet, save for the rhythmic clicking of your grandmother's knitting needles, a sound that felt like the heartbeat of the house...",
  },
  zh: {
    appName: '空灵档案员',
    archive: '档案',
    journal: '日志',
    moments: '瞬间',
    settings: '设置',
    record: '记录',
    chronologicalAnthology: '编年选集',
    memoirTitle: '档案员的回忆录',
    memoirDesc: '精心策划的回响与光影序列。每一段记忆都是灵魂的碎片，保存在时间的琥珀中。',
    captureNew: '捕捉新的片段？',
    journeyContinues: '你的旅程随着每一次呼吸和观察而继续。',
    recordNew: '记录新记忆',
    recordTitle: '记录你的故事',
    recordDesc: '轻声细语。这一刻永远属于你。',
    listening: '正在倾听沉默...',
    promptLabel: '今日提示',
    promptText: '“清晨的光芒今天向你揭示了什么？”',
    insightLabel: '记忆洞察',
    insightText: 'AI 将此记忆归类为 ',
    sensoryReflection: '感官反射',
    tipTitle: '档案员提示',
    tipText: '不用担心结构。只需描述颜色、气味和感受。稍后我会将它们编织成叙事。',
    selectionLabel: '选择',
    styleTitle: '叙事风格',
    styleDesc: '选择你的叙事风格',
    beginTranscription: '开始转录',
    skipForNow: '暂时跳过',
    archivalActive: '归档进程活跃',
    transcribingTitle: '将你的低语编织成丝绸...',
    weavingSilk: '正在将你的记忆编织成丝绸...',
    silkWoven: '你的记忆已编织完成。',
    poeticQuote: '“记忆是脆弱的；我们将它们编织成时间无法磨损的挂毯。”',
    audioMode: '音频模式',
    textMode: '文本模式',
    textPlaceholder: '在此输入你的记忆...',
    writing: '正在记录你的想法...',
    journalDesc: '你的个人叙事之旅，捕捉在低语与丝绸中。',
    entryLabel: '条目',
    settingsDesc: '自定义你的归档体验。',
    profileSettings: '个人资料设置',
    profileSettingsDesc: '管理你的个人信息和归档身份。',
    notifications: '通知',
    notificationsDesc: '控制接收归档提醒的方式和时间。',
    privacySecurity: '隐私与安全',
    privacySecurityDesc: '你的记忆是神圣的。管理你的数据保护。',
    languageRegion: '语言与地区',
    languageRegionDesc: '调整你的首选语言和地区设置。',
    defaultTranscript: '在午后阳光的柔和光芒下，一个安静的反思时刻。',
    currentFragment: '当前片段',
    springAfternoon: '1994年的春日午后',
    springDesc: '干燥路面上雨水的气息在空气中弥漫，我们坐在门廊上。世界很安静，除了你祖母织衣针有节奏的咔哒声，那声音听起来就像房子的心跳...',
  },
};

export const MEMORIES: Record<Language, Memory[]> = {
  en: [
    {
      id: '1',
      title: 'Whispers of the Inlet',
      date: 'April 14, 2024',
      quote: '"The tide carries secrets that the shore is too afraid to keep."',
      description: 'The salt air was heavy with the scent of coming storms and lost conversations.',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBWhD97FBe_OPx_j8yNORphpc7PuByF6R8ghOesV_ONOTp0Ti_AcJWAFjutZ-MJHRepLv_EKftMIMtgDbfC-NMf-KqAw_vmW2h4IZvGBAydDxH4A7oGp2mX69jpxYZPkEq1MEmFVll4k6OxuzTs53fnY7XIag5NYonH3m44Cajv2n578QzJUSmpAJtYmfg7rgImfHbooNOc0SJ0Pf3Sg5zxeQnAKxZE86f6L0RPYxSt5eLbgH5d-eQ1f7prfzsZ0H3YaY0AlJvcEXo',
    },
    {
      id: '2',
      title: 'Shadows in the Library',
      date: 'March 02, 2024',
      quote: '"We are made of the stories we never tell anyone."',
      description: 'Between the pages of an old botanical guide, I found the map to where we first met.',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAlD7NdnoYNXnwrwipOg-TTj0Eur9sI6QD1xsoJfaChvfAhv0jo5DHEEem_lc6Eb2sId6t88FIdaNPsxcE5WFnzgwDpeqE9PN7NKvC5KyGHRu1nb12l-PQ7VoTd2IVi5-6mZTm7xszu6zzUMIOuaOf9e6hBwvtgV6mDlmDLM3jPsNn1_lK5IPjtTpla1b-m9eBJV8TJLD5aLRZp4Ojs0m4X2ya4czzIRrzKsv8xqyK8mQKz1w_OEVn4nKQyUpMvgHJQ1YyydhjuXos',
    },
    {
      id: '3',
      title: 'The First Blossom',
      date: 'February 19, 2024',
      quote: '"Even the briefest bloom leaves a permanent stain on the wind."',
      description: 'The air turned sweet and the world felt vulnerable, waking up from its long white sleep.',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAGDx2cj7OULEgh5dNTQDBNDeJCI2W2rzl3-KAgHCLclKTgquoyXDLudL7n9rs3V2KqSBe4SvNbBJBChu8V2-JfvOsyXeQ5FJM6Fz7ix1t3CwdNO_vBRmEyTV7LhFa8EQz_KfrtTzv2448TMYPFecNdvMqTsON7fKsClrPrIIzwGYzXn7d2JzMSpIT-Pa8WNTWp_tF0DAkGWK3GUVyfQF-9091le8bTi9MaKYYT0Hv11J_oooKd3bxdt3AGFFh96yFVOOzEKamHoKA',
    },
  ],
  zh: [
    {
      id: '1',
      title: '小湾的私语',
      date: '2024年4月14日',
      quote: '“潮汐承载着海岸不敢保留的秘密。”',
      description: '咸咸的空气中弥漫着即将来临的风暴和遗失对话的气息。',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBWhD97FBe_OPx_j8yNORphpc7PuByF6R8ghOesV_ONOTp0Ti_AcJWAFjutZ-MJHRepLv_EKftMIMtgDbfC-NMf-KqAw_vmW2h4IZvGBAydDxH4A7oGp2mX69jpxYZPkEq1MEmFVll4k6OxuzTs53fnY7XIag5NYonH3m44Cajv2n578QzJUSmpAJtYmfg7rgImfHbooNOc0SJ0Pf3Sg5zxeQnAKxZE86f6L0RPYxSt5eLbgH5d-eQ1f7prfzsZ0H3YaY0AlJvcEXo',
    },
    {
      id: '2',
      title: '图书馆的阴影',
      date: '2024年3月2日',
      quote: '“我们是由从未告诉过任何人的故事组成的。”',
      description: '在旧植物指南的页码之间，我找到了我们第一次见面的地图。',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAlD7NdnoYNXnwrwipOg-TTj0Eur9sI6QD1xsoJfaChvfAhv0jo5DHEEem_lc6Eb2sId6t88FIdaNPsxcE5WFnzgwDpeqE9PN7NKvC5KyGHRu1nb12l-PQ7VoTd2IVi5-6mZTm7xszu6zzUMIOuaOf9e6hBwvtgV6mDlmDLM3jPsNn1_lK5IPjtTpla1b-m9eBJV8TJLD5aLRZp4Ojs0m4X2ya4czzIRrzKsv8xqyK8mQKz1w_OEVn4nKQyUpMvgHJQ1YyydhjuXos',
    },
    {
      id: '3',
      title: '第一朵花',
      date: '2024年2月19日',
      quote: '“即使是最短暂的绽放也会在风中留下永久的印记。”',
      description: '空气变得甜美，世界感到脆弱，从漫长的白色睡眠中醒来。',
      imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAGDx2cj7OULEgh5dNTQDBNDeJCI2W2rzl3-KAgHCLclKTgquoyXDLudL7n9rs3V2KqSBe4SvNbBJBChu8V2-JfvOsyXeQ5FJM6Fz7ix1t3CwdNO_vBRmEyTV7LhFa8EQz_KfrtTzv2448TMYPFecNdvMqTsON7fKsClrPrIIzwGYzXn7d2JzMSpIT-Pa8WNTWp_tF0DAkGWK3GUVyfQF-9091le8bTi9MaKYYT0Hv11J_oooKd3bxdt3AGFFh96yFVOOzEKamHoKA',
    },
  ],
};

export const NARRATIVE_STYLES: Record<Language, NarrativeStyle[]> = {
  en: [
    {
      id: 'poetry',
      name: 'Poetry',
      description: 'Lyrical, abstract, and rhythmic fragments',
      icon: 'Wind',
    },
    {
      id: 'novel',
      name: 'Novel',
      description: 'Expansive storytelling and deep character arcs',
      icon: 'BookOpen',
    },
    {
      id: 'essay',
      name: 'Essay',
      description: 'Reflective, analytical, and personal explorations',
      icon: 'PenTool',
    },
    {
      id: 'documentary',
      name: 'Documentary',
      description: 'Objective, archival, and factual observation',
      icon: 'Video',
    },
  ],
  zh: [
    {
      id: 'poetry',
      name: '诗歌',
      description: '抒情、抽象且有节奏的片段',
      icon: 'Wind',
    },
    {
      id: 'novel',
      name: '小说',
      description: '广阔的叙事和深刻的角色弧线',
      icon: 'BookOpen',
    },
    {
      id: 'essay',
      name: '散文',
      description: '反思、分析和个人探索',
      icon: 'PenTool',
    },
    {
      id: 'documentary',
      name: '纪录片',
      description: '客观、档案和事实观察',
      icon: 'Video',
    },
  ],
};
